from yacs.config import CfgNode as CN

_C = CN()

# MODEL
_C.MODEL = CN()
_C.MODEL.MODEL_NAME = 'efficientnet-b0'

# DATASET
_C.DATASET = CN()
_C.DATASET.NAME = "dataset"
_C.DATASET.PATH = "data/"
_C.DATASET.MEAN = [0.485, 0.456, 0.406]
_C.DATASET.STD = [0.229, 0.224, 0.225]

# DATALOADER
_C.DATALOADER = CN()
_C.DATALOADER.K_FOLD = 10
_C.DATALOADER.BATCH_SIZE = 4
_C.DATALOADER.IMAGE_SIZE = [256, 256]

# SOLVER
_C.SOLVER = CN()
_C.SOLVER.SEED = 0
_C.SOLVER.MAX_EPOCHS = 2
_C.SOLVER.LOG_PERIOD = 1
_C.SOLVER.TOLERANCE = 0.01
_C.SOLVER.PATIENCE = 5
_C.SOLVER.MIN_FOLD = 1

_C.OUTPUT_DIR = CN()
_C.OUTPUT_DIR = "log/debug"
